import "./project-management.test";
import "./page-switch.test";
import "./system-health-renderer.test";
import "./weekly-review.test";
import "./weekly-review-renderer.test";
import "./today-execution.test";
import "./today-execution-renderer.test";
import "./today-focus-strip-renderer.test";
import "./controlled-write.test";
import "./write-preview-modal.test";
import "./project-discovery.test";
import "./dashboard-operation-preview.test";
import "./portfolio-renderer.test";
import "./project-detail-renderer.test";
import "./portfolio-styles.test";
import "./vault-reader.test";
import "./live-git.test";
import "./git-activity-summary.test";

console.log("unit tests passed");
